Goals:

- Explain Numpy
- Why Numpy is non-negotiable for AI/ML & CV Roles
- Roadmap of what viewers will master in the playlist
- Motivate beginners

In [3]:
#Import libraries
import numpy as np
import time

In [15]:
# Numpy = Numerical Python
# Backbone of ML, DL, CV and DS

#Vector Addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

#Scalar Multiplication
weights = np.array([0.2, 0.5, 0.1])
learning_rate = 0.01

updated_weights = weights * learning_rate
print(updated_weights)

#Dot Product
features = np.array([1.5, 2.0, 3.0])
weights = np.array([0.4, 0.3, 0.2])

prediction = np.dot(features, weights)
print(prediction)

#Matrix Multiplication
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

W = np.array([[0.1],
              [0.2]])

output = np.dot(X, W)
print(output)

[5 7 9]
[0.002 0.005 0.001]
1.8000000000000003
[[0.5]
 [1.1]
 [1.7]]


In [16]:
#Python List Example
lis = [1,2,3,4,5]
print(lis)
print(type(lis))

[1, 2, 3, 4, 5]
<class 'list'>


In [17]:
#Numpy Array Example
arr = np.array(lis)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
#Key Difference between Python List and Numpy Array - Element-wise Operation
lis_add = lis * 2
print(lis_add)

arr_add = arr * 2
print(arr_add)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [19]:
#Performance Comparision
large_list = list(range(1_000_000))
large_array = np.array(large_list)

start = time.time()
[x * 2 for x in large_list]
print("List time:", time.time() - start)

start = time.time()
large_array * 2
print("NumPy time:", time.time() - start)

List time: 0.07240080833435059
NumPy time: 0.0028879642486572266


In [ ]:
#Summary
# - Python List are flexible but slow for math
# - Numpy arrays are fast and support vectorized operations
# - AI/ML relies heavily on numerical computation

# Roadmap 
1. ndarray basics

2. Array creation methods

3. Shape, dtype, memory layout

4. Indexing & slicing (1D, 2D, 3D)

5. Broadcasting (very important for ML)

6. Vectorized operations

7. Linear algebra essentials

8. Statistics for ML

9. Image-style array manipulation

10. Performance mindset (why NumPy is fast)