What is Numpy Array?

It is an Array class called ndarray where N represents N dimensional array and it can be 1, 2, 3 or more.

Characteristics of Numpy array:

1. All the elements are of same datatype

2. Once numpy arary is created total size of the array cannot be changed

3. In a 2D array each row of have the same no of columns

In [5]:
import numpy as np

In [3]:
#1D array

a1 = np.array([1,2,3,4,5,6])
print(a1)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
#2D Array

a2 = np.array([[1,2,3,4],[5,6,7,8],[2,3,4,8]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]
 [2 3 4 8]]
<class 'numpy.ndarray'>


In [10]:
print(a1[3])

4


In [11]:
print(a2[1,3])

8


In [17]:
#1-D array

print(np.ndim(a1))
print(np.shape(a1))
print(np.size(a1))
print(a1.dtype)

1
(6,)
6
int64


In [18]:
#2-D array

print(np.ndim(a2))
print(np.shape(a2))
print(np.size(a2))
print(a2.dtype)

2
(3, 4)
12
int64


In [23]:
np.zeros(2)

array([0., 0.])

In [24]:
np.ones(2)

array([1., 1.])

In [25]:
np.empty(2)

array([1., 1.])

In [27]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [28]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [31]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.linspace(0,10,5, dtype = np.int64)

array([ 0,  2,  5,  7, 10])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [35]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [38]:
np.diag([1,2,3,4,5],2)

array([[0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.diag(a2)

array([1, 6, 4])

In [39]:
np.vander(np.linspace(0,2,5), 2 )

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [40]:
np.vander([1,4,7,8,5], 2)

array([[1, 1],
       [4, 1],
       [7, 1],
       [8, 1],
       [5, 1]])

In [41]:
np.vander((1,2,3,4),4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [46]:
from numpy.random import default_rng

default_rng(42).random((2,3))

default_rng(42).random((2,3,2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

In [47]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])